# Generated by Django 5.2.4 on 2025-07-25 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_description_expense_name_expense_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='is_recurring',
        ),
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='expense',
            name='payment_method',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
